
FROM google/debian:wheezy

RUN apt-get update -y && apt-get install --no-install-recommends -y -q curl python build-essential git ca-certificates
RUN mkdir /nodejs && curl http://nodejs.org/dist/v0.10.33/node-v0.10.33-linux-x64.tar.gz | tar xvzf - -C /nodejs --strip-components=1

ENV PATH $PATH:/nodejs/bin

RUN git clone git@github.com:omerxi/omerxi.git
RUN  cd omerxi

#WORKDIR /app
#ONBUILD ADD . /app
#ONBUILD RUN npm install
#EXPOSE 8080
#CMD []
#ENTRYPOINT ["/nodejs/bin/npm", "start"]
